<?php
return array(
	"无名之辈"=>array(
	    "name"=>"无名之辈",
		"level"=>"0",
		"need_integral"=>"0",
		"min"=>"0",
	    "max"=>"99",
	    "remark"=>""
	),
	 "初涉茅庐"=>array( 
	    "name"=>"初涉茅庐",
		"level"=>"1",
		"need_integral"=>"200",
		"min"=>"100",
	    "max"=>"299",
	    "remark"=>""
	),
	 "仗剑天涯"=>array(
	    "name"=>"仗剑天涯",
		"level"=>"2",
		"need_integral"=>"300",
		"min"=>"300",
	    "max"=>"599",
	    "remark"=>""
	),
	 "崭露头角"=>array( 
	     "name"=>"崭露头角",
		"level"=>"3",
		"need_integral"=>"400",
		"min"=>"600",
	    "max"=>"999",
	    "remark"=>""
	),
	"锋芒毕露"=>array( 
	    "name"=>"锋芒毕露",
		"level"=>"4",
		"need_integral"=>"500",
		"min"=>"1000",
	    "max"=>"1499",
	    "remark"=>""
	),
	"声名鹊起"=>array( 
	    "name"=>"声名鹊起",
		"level"=>"5",
		"need_integral"=>"600",
		"min"=>"1500",
	    "max"=>"2099",
	    "remark"=>""
	),
	"如日中天"=>array( 
	    "name"=>"如日中天",
		"level"=>"6",
		"need_integral"=>"700",
		"min"=>"2100",
	    "max"=>"2799",
	    "remark"=>""
	),
	"名扬四海"=>array( 
	    "name"=>"名扬四海",
		"level"=>"7",
		"need_integral"=>"800",
		"min"=>"2800",
	    "max"=>"3599",
	    "remark"=>""
	),
	 "威震八方"=>array( 
	     "name"=>"威震八方",
		"level"=>"8",
		"need_integral"=>"900",
		"min"=>"3600",
	    "max"=>"4499",
	    "remark"=>""
	),
	 "独步天下"=>array( 
	     "name"=>"独步天下",
		"level"=>"9",
		"need_integral"=>"1000",
		"min"=>"4500",
	    "max"=>"5499",
	    "remark"=>""
	),
	 "英雄豪杰"=>array( 
	     "name"=>"英雄豪杰",
		"level"=>"10",
		"need_integral"=>"1100",
		"min"=>"5500",
	    "max"=>"6599",
	    "remark"=>""
	),
	 "武林盟主"=>array( 
	     "name"=>"武林盟主",
		"level"=>"11",
		"need_integral"=>"1200",
		"min"=>"6600",
	    "max"=>"7799",
	    "remark"=>""
	),
	 "一代宗师"=>array( 
	     "name"=>"一代宗师",
		"level"=>"12",
		"need_integral"=>"1300",
		"min"=>"7800",
	    "max"=>"9099",
	    "remark"=>""
	),
    "笑傲江湖"=>array( 
        "name"=>"笑傲江湖",
		"level"=>"13",
		"need_integral"=>"1400",
		"min"=>"9100",
	    "max"=>"10499",
	    "remark"=>""
	),
    "飘然归隐"=>array( 
        "name"=>"飘然归隐",
		"level"=>"14",
		"need_integral"=>"1500",
		"min"=>"10500",
	    "max"=>"11999",
	    "remark"=>""
	),
    "独孤求败"=>array( 
        "name"=>"独孤求败",
		"level"=>"15",
		"need_integral"=>"1600",
		"min"=>"12000",
	    "max"=>"",
	    "remark"=>""
	),
    "sign_num"=>array(
        "6"=>array( 
            "min_day"=>"0",
    		"max_day"=>"6",
    		"point"=>"15",
    		"gold"=>"20"
    	),
        "15"=>array( 
            "min_day"=>"6",
    		"max_day"=>"15",
    		"point"=>"20",
    		"gold"=>"30"
    	),
        "30"=>array( 
            "min_day"=>"15",
    		"max_day"=>"30",
    		"point"=>"25",
    		"gold"=>"40"
    	),
        "31"=>array( 
            "min_day"=>"30",
    		"max_day"=>"",
    		"point"=>"35",
    		"gold"=>"55"
    	)
    )
);
